Config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include('main.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from main import views

app_name = 'main'

urlpatterns = [
    path('home/', views.home, name='home'),
    path('contact/', views.contact, name='contact'),
]

main/models.py
from django.db import models

class Person(models.Model):
    name = models.CharField(max_length=50)
    age = models.IntegerField()
    position = models.CharField(max_length=30)
    city = models.CharField(max_length=10)
    image = models.ImageField(upload_to='img')
    description = models.TextField(max_length=1000)

    def __str__(self):
        return self.name


class Contact(models.Model):
    number = models.IntegerField(verbose_name='номер')
    adres = models.CharField('адрес',max_length=50)

    def __str__(self):
        return self.adres

# 1)python3 manage.py makemigrations
# 2)python3 manage.py migrate
# 3)python3 manage.py createsuperuser
# 4)python3 manage.py runserver
# templates

main/views.py
from django.shortcuts import render

import main.views
from main.models import Person, Contact


def home(requests):
    persons = Person.objects.all()
    condext = {
        'persons': persons
    }

    return render(requests, 'main/home.html', condext)


def contact(requests):
    contacts = Contact.objects.all()
    context = {
        'contacts': contacts
    }
    return render(requests, 'main/contact.html', context)

templates/main/contact.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
{% for l in contacts %}
{{l.number}}
{{l.adres}}
{% endfor %}
<a href="{% url 'main:home' %}">назад</a>
</body>
</html>

templates/main/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>history</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

</head>
<body>

<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="#">biografia</a>
        </div>
        <ul class="nav navbar-nav">
            <li><a href="{% url 'main:home' %}">home</a></li>
            <li><a href="#">about</a></li>
            <li><a href="{% url 'main:contact' %}">Contacts</a></li>
            <li><a href="#">register</a></li>
        </ul>
    </div>
</nav>
{% for k in persons %}
<h2>аты: {{ k.name }}</h2>
<h4>{{ k.age }}</h4>
<img src="{{ k.image.url }}" style="width:200px; height:200px">
<h4>{{ k.position }}</h4>
<h3>{{ k.city }}</h3>
<p>{{ k.description }}</p>
{% endfor %}

<h2> hello my friends! </h2>
</body>
</html>